services:
#  ecommerce_api:
#    image: lima-ecommerce-api
#    build: .
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - mynetwork
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/e-commerce?allowPublicKeyRetrieval=true
#      - spring.datasource.username=<my-username>
#      - spring.datasource.password=<my-password>
#      - springdoc.api-docs.path=/api-docs
#
#    depends_on:
#      - mysqldb

  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    networks:
      - mynetwork
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: fabiolima
      MYSQL_PASSWORD: fabiolima123
      MYSQL_ROOT_PASSWORD: fabiolimaR123

    volumes:
        - ./MySQL/initdb:/docker-entrypoint-initdb.d
        - ./MySQL/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb  # Link to MySQL container
      MYSQL_ROOT_PASSWORD: fabiolimaR123
    ports:
      - 8090:80  # Expose phpMyAdmin on port 8090
    depends_on:
      - mysqldb
    networks:
      - mynetwork

networks:
  mynetwork: