DROP SCHEMA IF EXISTS `ONLINE-SHOP`;

CREATE SCHEMA `ONLINE-SHOP`;

USE `ONLINE-SHOP`;

-- User Table
CREATE TABLE User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    address TEXT,
    role ENUM('CUSTOMER', 'ADMIN') NOT NULL,
    status ENUM('ENABLED', 'DISABLED') NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Category Table
CREATE TABLE Category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Product Table
CREATE TABLE Product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock INT DEFAULT 0,
    category INT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY FK_CATEGORY_idx (category),
    CONSTRAINT FK_CATEGORY FOREIGN KEY (category) REFERENCES Category(id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Basket (Cart) Table
CREATE TABLE Basket (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    status ENUM('OPEN', 'CHECKED-OUT') DEFAULT 'OPEN',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY FK_USER_idx (user_id),
    CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES User(id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- BasketItem Table
CREATE TABLE BasketItem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    basket_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY FK_BASKET_idx (basket_id),
    KEY FK_PRODUCT_idx (product_id),
    CONSTRAINT FK_BASKET FOREIGN KEY (basket_id) REFERENCES Basket(id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_PRODUCT FOREIGN KEY (product_id) REFERENCES Product(id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Order Table
CREATE TABLE `Order` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    basket_id INT NOT NULL,
    totalPrice DECIMAL(10, 2) NOT NULL,
    paymentStatus ENUM('PENDING', 'PAID', 'FAILED') DEFAULT 'PENDING',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY FK_ORDER_USER_idx (user_id),
    KEY FK_ORDER_BASKET_idx (basket_id),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (user_id) REFERENCES User(id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_ORDER_BASKET FOREIGN KEY (basket_id) REFERENCES Basket(id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Payment Table
CREATE TABLE Payment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    paymentMethod VARCHAR(255) NOT NULL,
    status ENUM('PENDING', 'COMPLETED', 'FAILED') DEFAULT 'PENDING',
    transactionId VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY FK_PAYMENT_ORDER_idx (order_id),
    CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (order_id) REFERENCES `Order`(id) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

