spring:
  application:
    name: e-commerce

  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    username: springstudent
    password: springstudent

#  error:
#    include-message: always
logging:
  level:
    org.springframework.web: DEBUG   # For HTTP request/response details
    org.springframework.security: DEBUG   # For Spring Security related debugging
    com.fabiolima: DEBUG   #

paypal:
  client-id: "Ac8zvk-hlrlrO1Gm-dEpIW44OBZrfYDodhyflSx71a1d4CNj0-SvIi1WBh_L7bZRWj_tCvsT3L5rnnux"
  client-secret: "EG3hZRfneY6OwcwPMALp1RvtzZ_yNgQkmQbdCGwgHxeMfXUujO_PzP45uJ-xXBRbxDhnAzrrEnqge8So"
  mode: sandbox

